// El Arca de Noé — archivo de letras · trece canciones · 1999–2000
export const CANCIONES = [
  {
    n: '01', t: 'Bolboretas', idioma: 'gallego', dur: '3:06',
    audio: 'audio/01-bolboretas.mp3',
    frase: 'berros contra a fiestra',
    nota: 'varias palabras quedan enmascaradas por la música y la dicción cantada.',
    letra: [
      'Uns berros entre catro paredes,',
      '[¿bolboretas loitan pola fiestra?].',
      'E son a última merda no blues.',
      '',
      'As ondas ruxen no mar,',
      'o vento zoa no ar,',
      'e son a última merda no blues.',
      '',
      'Chega, meu príncipe, [¿meus señores?],',
      'faime voar entre [inaudible, 01:07–01:17] amores.',
      'Rexeita por miñas verbas [inaudible, 01:17–01:26].',
      '',
      'E xa sei: viu o paxaro',
      'que seguiu o teu paso.',
      '',
      'Uns berros entre catro paredes,',
      '[¿bolboretas loitan pola fiestra?].',
      'E son a última merda no blues.',
      '',
      'As ondas ruxen no mar,',
      'o vento zoa no ar,',
      'e son a última merda no blues.',
      '',
      'Oh, oh, oh…',
    ],
  },
  {
    n: '02', t: 'De ti y de mí', idioma: 'castellano', dur: '4:06',
    audio: 'audio/02-de-ti-y-de-mi.mp3',
    frase: 'arena donde hubo mar',
    nota: 'salvo una palabra indicada.',
    letra: [
      'De la misma razón que del frío al calor,',
      'de que salga la luna y se ponga el sol,',
      'de mucho, de poco, de nada y de todo,',
      'de ti, de mí.',
      '',
      'De los mil versos que te [¿pude?] escribir,',
      'de saber si te quiero me queda por vivir,',
      'de mucho, de poco, de nada y de todo,',
      'de ti y de mí.',
      '',
      'De tu querer no hay que buscar',
      'en otro momento, en otro lugar.',
      'De tu querer rompe el cristal',
      'que hace la magia y hace arena el mar.',
      '',
      'De sentir el vacío y tenerte aquí,',
      'de la lluvia en los ojos, tanto invierno sin fin,',
      'de mucho, de poco, de nada y de todo,',
      'de ti y de mí.',
      '',
      'De la vida vivida y lo que ha de venir,',
      'de lo que hemos sufrido y lo que hay que sufrir,',
      'de mucho, de poco, de nada y de todo,',
      'de ti y de mí.',
      '',
      'De tu querer no hay que buscar',
      'en otro momento, en otro lugar.',
      'De tu querer rompe el cristal',
      'que hace la magia y hace arena el mar.',
      '',
      'De la misma razón que del frío al calor,',
      'de que salga la luna y se ponga el sol,',
      'de mucho, de poco, de nada y de todo,',
      'de ti y de mí,',
      'de ti y de mí,',
      'de ti y de mí.',
      '',
      '(Voz hablada: «Gracias».)',
    ],
  },
  {
    n: '03', t: 'Ioeo', idioma: 'latín', dur: '2:19',
    audio: 'audio/03-ioeo.mp3',
    frase: 'la vida canta tu nombre',
    nota: '',
    letra: [
      'Ioeo, cantet te vita... (x9)',
      '',
      'Ah, ah, ah...',
      'Ah, ah...',
      '',
      'Peri, sumet, canit, suae.',
      'Peri, sumet, canit, si vere.',
      '',
      'Ioeo, cantet te vita... (x8)',
      '',
      'Ah, ah, ah...',
      'Ah, ah...',
      '',
      'Peri, sumet, canit, suae.',
      'Peri, sumet, canit, si vere.',
      '',
      'Ioeo, cantet te vita... (x9)',
      '',
      'Ah, ah, ah...',
      'Ah, ah...',
    ],
  },
  {
    n: '04', t: 'Irmán de Breogán', idioma: 'gallego', dur: '4:02',
    audio: 'audio/04-irman-de-breogan.mp3',
    frase: 'a infancia chama de lonxe',
    nota: 'la parte cantada más inteligible ocupa aproximadamente del minuto 1 al 6; después hay repeticiones, vocalizaciones y voces de ensayo.',
    letra: [
      'Nos corpos da lúa',
      'mirabámonos.',
      '',
      '[Inaudible, 01:09–01:49.]',
      '',
      'E precisareite.',
      'Abrázame,',
      '[¿e mírame?], irmán.',
      'Protéxeme',
      'do mundo que hai fóra.',
      '',
      'Creceremos',
      'e cada un tomará o seu camiño.',
      'Te casarás,',
      'eu casarei.',
      'Ti [inaudible, 03:11–03:28],',
      'eu recordareite, irmán.',
      '',
      'Cando un día fomos nenos,',
      'cantos recordos levamos,',
      'cando xa',
      'non nos precisamos.',
      '',
      'E mírame,',
      'e quéreme coma antes,',
      '[inaudible, 04:15–04:23].',
      '',
      'Quero sentar',
      'nos teus xeonllos',
      'e falar do que sentimos, hermano.',
      'Todo rematará.',
      '',
      'E quero [inaudible, 05:41–06:01] contigo.',
      'Serei sincera contigo, irmán.',
      'Serei sincera contigo.',
      '',
      '[Vocalización: «sálvame» repetido.]',
      '[Vocalización: «chao/chau» repetido.]',
      '[Voces de ensayo no inteligibles hasta el final de la pista.]',
    ],
  },
  {
    n: '05', t: 'Mía', idioma: 'castellano', dur: '3:17',
    audio: 'audio/05-mia.mp3',
    frase: 'volver con las manos llenas',
    nota: 'salvo una frase indicada.',
    letra: [
      'Nada tengo que ver,',
      'nada puedo saber',
      'de tu alma, mi vida,',
      'de quererte otra vez,',
      'de perderte en la orilla,',
      'de tocarte la piel',
      'y saber si eres mía.',
      '',
      '[¿Con piel y con piel?]',
      'Y saber si eres mía.',
      '',
      'No te pude querer,',
      'no lo supe hacer bien.',
      'Tuve tanto miedo,',
      'me dolía perder.',
      '',
      'Me podría arrepentir,',
      '¿y de qué iba a servir?',
      'Solo quiero que vengas',
      'a empezar a vivir',
      'y saber que eres mía.',
      '',
      'Y ahora vuelvo a ti',
      'con las manos llenas',
      'de ilusiones, besos,',
      'promesas eternas,',
      'y saber si eres mía,',
      'mía.',
    ],
  },
  {
    n: '06', t: 'No quiero vivir', idioma: 'castellano', dur: '5:18',
    frase: 'amarte es sangrar despacio',
    nota: 'con dos versos de lectura probable.',
    letra: [
      'Dicen que quererte',
      'es una enfermedad que tiende a matar.',
      'Que tus besos quitan [¿amarga salida?],',
      'como arena al mar.',
      '',
      'Dicen que quererte',
      'es una enfermedad que tiende a matar.',
      'De tus ojos, pecado eterno pasado,',
      'para no recordar.',
      '',
      'Quererte sería morirme día a día,',
      'creyendo tus sucias y crueles mentiras.',
      'Maldito mi fin,',
      'maldito el día que te conocí.',
      '¿Por qué sin ti no quiero vivir?',
      '',
      'Dicen que quererte',
      'es una enfermedad que tiende a matar.',
      'Lenta y suavemente',
      '[¿hieres mi corazón?] y vuelvo a sangrar.',
      '',
      'Dicen que quererte',
      'es una enfermedad que tiende a matar.',
      'Y puñales clavas,',
      'mortales palabras no podré curar.',
      '',
      'Quererte sería morirme día a día,',
      'creyendo tus sucias y crueles mentiras.',
      'Maldito mi fin,',
      'maldito el día que te conocí.',
      '¿Por qué sin ti no quiero vivir?',
      '',
      'No quiero vivir.',
      'No quiero vivir.',
      'No quiero vivir.',
      'No quiero vivir.',
    ],
  },
  {
    n: '07', t: 'Por haberte perdido', idioma: 'castellano', dur: '2:49',
    audio: 'audio/07-por-haberte-perdido.mp3',
    frase: 'un amanecer sin tu piel',
    nota: '',
    letra: [
      'Intentando soportar',
      'esta mala soledad,',
      'de tu vacío,',
      'ese raro amanecer,',
      'de abrazar y no poder',
      'tocar tu piel.',
      '',
      'No volverás',
      'a mirar atrás,',
      'en el camino',
      'que separó mi destino',
      'de tus besos y los míos,',
      'de tu luz y tu calor,',
      'de las lágrimas y el olvido',
      'que quedaron por tenerte',
      'y por haberte perdido.',
      '',
      'Esta dulce sensación,',
      'mi alcohol y confusión',
      'por mi sangre;',
      'que se altera si tú estás,',
      'que se para si te vas',
      'de mi vera.',
      '',
      'Volverás',
      'a mirar atrás,',
      'en el camino',
      'que separó mi destino',
      'de tus besos y los míos,',
      'de tu luz y tu calor,',
      'de las lágrimas y el olvido',
      'que quedaron por tenerte',
      'y por haberte perdido.',
    ],
  },
  {
    n: '08', t: 'Rompiendo los cristales', idioma: 'castellano', dur: '3:42',
    audio: 'audio/08-rompiendo-los-cristales.mp3',
    frase: 'renacer al otro lado',
    nota: 'se señalan dos versos poco nítidos.',
    letra: [
      '¿Cuántas veces, atrapada entre tus garras,',
      'deshiciste los recuerdos de mis lágrimas?',
      'Sorteando entre los muebles',
      'las heridas de tus balas,',
      '[inaudible, 01:04–01:09].',
      '',
      'Y suéltame,',
      'déjame ver la ventana,',
      'déjame saltar y verte',
      'cómo lloras por no tenerme,',
      'mientras asoman en tus uñas',
      'jirones de mi piel.',
      '',
      'Hace años [¿soñé?] contigo,',
      'el peor de los castigos,',
      'primaveras enterradas',
      'en pos de una nueva vida.',
      '',
      'Sin amor y sin dinero',
      'llegarán mejores tiempos;',
      'y mirar al horizonte,',
      'y cantar al viento libre,',
      'caminar sobre las aguas',
      'y volar.',
      '',
      'Haré una nueva vida',
      'allí donde no puedas verme,',
      'lloraré por no quererte,',
      'lucharé por renacer.',
      '',
      'Y suéltame,',
      'déjame ver la ventana,',
      'déjame saltar y verte',
      'cómo lloras por no tenerme,',
      'mientras asoman en tus uñas',
      'jirones de mi piel.',
      '',
      'Mientras asoman en tus uñas,',
      'jirones de mi piel.',
      '',
      'Y suéltame,',
      'déjame ver la ventana,',
      'déjame saltar y verte',
      'cómo lloras por no tenerme,',
      'mientras asoman en tus uñas',
      'jirones de mi piel.',
      '',
      'Asoman en tus uñas',
      'jirones de mi piel.',
      'Asoman en tus uñas',
      'jirones de mi piel,',
      'jirones de mi piel,',
      'de mi piel.',
    ],
  },
  {
    n: '09', t: 'Sin ti me muero', idioma: 'castellano', dur: '3:17',
    audio: 'audio/09-sin-ti-me-muero.mp3',
    frase: 'gritos desde el destierro',
    nota: 'a partir de aproximadamente 02:21 predomina el desarrollo instrumental.',
    letra: [
      'Sin ti me muero,',
      'sin ti no puedo.',
      'El aire que sin remedio',
      'expulso de mis recuerdos.',
      '',
      'La luz de la memoria',
      'acariciando el suelo,',
      'mis besos desgastados',
      'buscando tu consuelo.',
      '',
      'Sin ti me muero,',
      'sin ti no puedo,',
      'a gritarte desde el destierro',
      'todo lo que yo te siento.',
      '',
      'No tengo tus miradas',
      'en mi castigo eterno.',
      'No llores más, vida mía,',
      'que pronto nos tendremos.',
      '',
      'Sin ti me muero.',
      'Ah, sin ti no puedo.',
      'Ah, el aire que sin remedio',
      'expulso de mi recuerdo.',
    ],
  },
  {
    n: '10', t: 'Sola', idioma: 'castellano', dur: '4:19',
    audio: 'audio/10-sola.mp3',
    frase: 'jazmines después del llanto',
    nota: 'excepto una estrofa parcialmente cubierta por la música.',
    letra: [
      'Sangrando canciones',
      'y ganas de llorar,',
      'me pierdo en el bosque',
      'y vuelvo a despertar.',
      '',
      'Sola, sola,',
      'me vuelvo a despertar.',
      'Sola, sola,',
      'me vuelvo a despertar.',
      '',
      'Me sorprende el sol',
      'con los ojos hinchados.',
      'Me cautiva el olor',
      'de jazmines tempranos.',
      '',
      'Sola, sola,',
      'me vuelvo a despertar.',
      'Sola, sola,',
      'me vuelvo a despertar.',
      '',
      'Me rodean altas copas,',
      'me miran sin bajar.',
      '[¿A besar labios mojados?]',
      '[Inaudible, 02:28–02:34.]',
      '',
      'Sola, sola,',
      'me vuelvo a despertar.',
      'Sola, sola,',
      'me vuelvo a despertar.',
      '',
      'El día avanza',
      'y yo en el mismo lugar,',
      'mirando al frente,',
      'esperando verte llegar.',
      '',
      'Sola, sola,',
      'me vuelvo a despertar.',
      'Sola, sola,',
      'me vuelvo a despertar.',
      'Sola, sola,',
      'me voy a despertar.',
      'Sola, sola, sola…',
    ],
  },
  {
    n: '11', t: 'Soños', idioma: 'gallego', dur: '2:23',
    audio: 'audio/11-sonos.mp3',
    frase: 'soños vellos ao solpor',
    nota: 'la primera estrofa y parte de la segunda quedan poco definidas en la mezcla.',
    letra: [
      'Soños',
      'que dormen vellos en paz,',
      'agardan que algún trasno',
      'esperte ao solpor.',
      '',
      'Soños',
      'que velan polas rúas,',
      '[inaudible, 00:18–00:30],',
      'mirando no camiño',
      'algún demo saltar.',
      '',
      'Soños,',
      '[¿de idades sempre vellas?],',
      'mirando pola [inaudible],',
      '[inaudible] do lugar.',
      '',
      'Campos verdes sobre o mar,',
      'os animais falando',
      'do que ha de pasar.',
      'Flores, sorrindo cara ao ceo,',
      'mil noites de treboada,',
      'abríndose o sol.',
      '',
      'Soños,',
      'de xente [inaudible],',
      'de pobos de saudades,',
      'dun bico, sempre amor.',
    ],
  },
  {
    n: '12', t: 'Tequila y Ron', idioma: 'gallego', dur: '1:34',
    audio: 'audio/12-tequila-y-ron.mp3',
    frase: 'raparigas e vellos bailando',
    nota: 'fragmento. la grabación contiene solo una frase breve.',
    letra: [
      'E aínda [¿as?] raparigas',
      'e os homes vellos',
      'bailando son.',
      '',
      'Son tempos de [inaudible, 00:20–00:22].',
    ],
  },
  {
    n: '13', t: 'Un día', idioma: 'castellano', dur: '3:33',
    audio: 'audio/13-un-dia.mp3',
    frase: 'querer sin pertenecer',
    nota: '',
    letra: [
      'El color de tus ojos no importa.',
      'Me da igual que seas mía,',
      'me da igual que estés sola.',
      '',
      '[La transcripción se interrumpe aquí.]',
    ],
  },
];
